### ISSUE TITLE
Please oh please don't import * for psg.....

### ISSUE THREAD

**Issue by PySimpleGUI** [KingOfTNT10/WordSearchPuzzleGenerator#1]
Really trying to not have PySimpleGUI fall prey to the import * like tkinter did.

I'm looking forward to seeing what your puzzle looks like... post a screenshot in your readme and I'm sure you'll get plenty of attention!  What a great idea for a GUI.  I don't think I've seen anyone make one using PySimpleGUI.

**Comment by PySimpleGUI** [comment]
While I've got your attention.... you can include your images in your py file really easily.  If you pip install psgresizer you can easily convert them to BASE64 encoded bytyestrings that can be put into your code and passed to PySimpleGUI.

There are a couple of demo programs that also do the encoding for you.  For small images, in particular, it's nice because you end up with just 1 file, your .py file.

**Comment by K9Developer** [comment]
> Really trying to not have PySimpleGUI fall prey to the import * like tkinter did.
> 
> I'm looking forward to seeing what your puzzle looks like... post a screenshot in your readme and I'm sure you'll get plenty of attention!  What a great idea for a GUI.  I don't think I've seen anyone make one using PySimpleGUI.
> 

Thank you! Ill be sure to update it. But why shouldnt i do import *?

**Comment by PySimpleGUI** [comment]
Thank you for being open and wanting to learn!

I'm glad you asked.

Jason did a good job of describing the problem in this issue:

https://github.com/PySimpleGUI/PySimpleGUI/issues/4913

You'll find a good number of articles written about import *.  The big problem is "namespace pollution".  I can't boil it down at the moment to a few phrases.  Take a look at the issue and see if it has a good answer for you.

Keep learning, asking questions, building stuff..... awesome things to see an engineer doing.

**Comment by PySimpleGUI** [comment]
OMG!  I had not seen your screenshots and added into in your readme until just now!

Great job! Visitors are going to ❤ seeing those pictures.

Way to go!

![image](https://user-images.githubusercontent.com/46163555/144720650-170829f1-76a7-4274-8f68-5dd1f359a7f3.png)

**Comment by PySimpleGUI** [comment]
Oh!  AND you already changed your code.  You're using docstrings too.  I'm seriously impressed.  Great stuff... really great stuff.

**Comment by PySimpleGUI** [comment]
> I'm very greatful for that

AND you said this in your readme??  Seriously?  Sharing your story.... sharing your gratitude. Wow.... you're awesome.

**Comment by K9Developer** [comment]
> > I'm very greatful for that
> 
> AND you said this in your readme??  Seriously?  Sharing your story.... sharing your gratitude. Wow.... you're awesome.

Thank you so much!!!!! 😃I really i appreciate you saying that!

**Comment by PySimpleGUI** [comment]
You're quite welcome!  Geez... it's the least I can do.  I do appreciate it.  This entire experience with the PySimpleGUI users is really incredible.  I've never seen a more openly grateful group of people on the internet.  It feels really special to me and I appreciate you helping be a part of that vocal group of supporters.  Priceless is a term I find myself using more and more.
